In [1]:
#Benjamin Adolfo Naranjo Lopez
#21687575-3
#15-04-26

In [2]:
import pandas as pd

df = pd.read_csv("ventas_historicas.csv")

df.shape
df.dtypes
df.head()
df.isnull().sum()

id_venta        0
mes             0
region          0
vendedor       21
categoria       0
canal          11
cantidad        0
precio_unit     0
descuento      11
monto_bruto     0
dtype: int64

In [3]:
filtro = (df['region'] == 'Centro') & (df['monto_bruto'] > 300)
df_filtrado = df[filtro]

len(df_filtrado)

47

In [4]:
df_online = df[
    (df['canal'] == 'Online') & (df['descuento'] >= 15)
][['region', 'categoria', 'cantidad', 'monto_bruto', 'descuento']]

print(df_online)

     region    categoria  cantidad  monto_bruto  descuento
2     Oeste       Tablet        13      4876.82       15.0
5       Sur      Monitor         7      1951.18       15.0
7    Centro       Tablet         4      1508.76       20.0
20    Norte  Auriculares         7       958.65       20.0
23    Oeste       Laptop         7      5688.69       20.0
36      Sur       Tablet        12      4683.96       20.0
48    Oeste      Teclado        11       804.43       20.0
49      Sur       Tablet         9      2735.10       20.0
60    Oeste  Auriculares        10      1311.50       15.0
70    Norte  Auriculares        12      1532.64       20.0
90    Oeste      Monitor         5      1653.60       20.0
112    Este       Tablet        14      4457.88       15.0
132   Oeste        Mouse         5       214.90       20.0
133   Norte      Teclado         3       195.42       15.0
149   Oeste       Tablet         2       619.72       20.0
159    Este       Tablet         4      1302.96       20.0
179  Centro  Auriculares         7       882.98       20.0
191  Centro      Monitor         2       584.38       20.0
204  Centro       Tablet         2       649.80       15.0
228    Este  Auriculares         5       600.35       20.0
237  Centro  Auriculares        14      1876.98       20.0
282     Sur  Auriculares        10      1323.60       15.0
289     Sur        Mouse         1        39.49       20.0
297  Centro       Laptop         1      1036.18       20.0

In [5]:
df_cat = df[df['categoria'].isin(['Laptop', 'Tablet'])]

len(df_cat)

97

In [6]:
df_between = df[df['cantidad'].between(8, 15)]
df_between.sort_values(by='monto_bruto').head(10)

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
195,1196,Marzo,Oeste,Ana Torres,Mouse,Mayorista,8,33.47,15.0,267.76
189,1190,Junio,Oeste,Roberto Fuentes,Mouse,Tienda fisica,9,29.86,0.0,268.74
73,1074,Marzo,Norte,Roberto Fuentes,Mouse,Tienda fisica,8,34.52,0.0,276.16
83,1084,Abril,Sur,Roberto Fuentes,Mouse,Online,8,34.62,0.0,276.96
76,1077,Abril,Este,Laura Diaz,Mouse,Mayorista,10,30.59,15.0,305.90
160,1161,Mayo,Oeste,Ana Torres,Mouse,Mayorista,9,37.80,15.0,340.20
161,1162,Abril,Sur,NaN,Mouse,Mayorista,11,30.95,0.0,340.45
208,1209,Enero,Centro,Javier Munoz,Mouse,Tienda fisica,8,43.60,10.0,348.80
224,1225,Junio,Oeste,Ana Torres,Mouse,Online,12,30.37,5.0,364.44
125,1126,Marzo,Este,Javier Munoz,Mouse,Online,10,36.85,0.0,368.50

In [7]:
# and y or funcionan como booleanos y &,| funciona de elemento a elementro, and genera errores en pandas
#.isin es mas ligre  pero | es mas escalable con varios valores

In [8]:
df_filtro = df[
    (df['mes'].isin(['Enero', 'Febrero'])) &
    (df['categoria'].isin(['Laptop', 'Tablet'])) &
    (df['descuento'] > 10)
]

In [9]:
df_filtro.nlargest(5, 'monto_bruto')

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
23,1024,Febrero,Oeste,Camila Vega,Laptop,Online,7,812.67,20.0,5688.69
157,1158,Febrero,Este,Ana Torres,Tablet,Tienda fisica,15,378.21,15.0,5673.15
187,1188,Febrero,Oeste,Javier Munoz,Tablet,Mayorista,12,312.03,20.0,3744.36
297,1298,Enero,Centro,Laura Diaz,Laptop,Online,1,1036.18,20.0,1036.18
15,1016,Febrero,Centro,Roberto Fuentes,Tablet,Mayorista,3,305.93,20.0,917.79

In [10]:
promedio = df['monto_bruto'].mean()

df_ns = df[
    (df['region'].isin(['Norte', 'Sur'])) &
    (df['cantidad'] >= 10) &
    (df['monto_bruto'] > promedio)
]

In [11]:

df['region'].value_counts()


df_ns['region'].value_counts()

region
Norte    13
Sur       9
Name: count, dtype: int64

In [12]:
def filtrar_ventas(df, region, categoria, monto_minimo):
    return df[
        (df['region'] == region) &
        (df['categoria'] == categoria) &
        (df['monto_bruto'] >= monto_minimo)
    ]

filtrar_ventas(df, 'Centro', 'Laptop', 500)

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
11,1012,Junio,Centro,Carlos Rivas,Laptop,Mayorista,15,905.07,0.0,13576.05
30,1031,Junio,Centro,Laura Diaz,Laptop,Mayorista,2,1041.74,0.0,2083.48
127,1128,Mayo,Centro,Laura Diaz,Laptop,NaN,3,815.41,20.0,2446.23
130,1131,Junio,Centro,Carlos Rivas,Laptop,Tienda fisica,8,947.56,5.0,7580.48
131,1132,Marzo,Centro,Camila Vega,Laptop,NaN,5,953.09,10.0,4765.45
148,1149,Junio,Centro,Camila Vega,Laptop,Mayorista,6,728.70,0.0,4372.20
150,1151,Junio,Centro,Javier Munoz,Laptop,Mayorista,3,925.56,0.0,2776.68
158,1159,Enero,Centro,Ana Torres,Laptop,Tienda fisica,4,1006.39,10.0,4025.56
269,1270,Mayo,Centro,Maria Lopez,Laptop,Tienda fisica,6,789.51,0.0,4737.06
277,1278,Junio,Centro,Roberto Fuentes,Laptop,Mayorista,4,1059.02,0.0,4236.08
297,1298,Enero,Centro,Laura Diaz,Laptop,Online,1,1036.18,20.0,1036.18

In [13]:
filtrar_ventas(df, 'Norte', 'Tablet', 300)

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
10,1011,Junio,Norte,Maria Lopez,Tablet,Mayorista,7,348.34,5.0,2438.38
116,1117,Enero,Norte,Javier Munoz,Tablet,Online,10,313.44,0.0,3134.40
211,1212,Febrero,Norte,Roberto Fuentes,Tablet,Tienda fisica,15,303.75,0.0,4556.25
221,1222,Mayo,Norte,Camila Vega,Tablet,Mayorista,3,365.17,0.0,1095.51
225,1226,Mayo,Norte,Laura Diaz,Tablet,Online,14,389.30,10.0,5450.20
281,1282,Abril,Norte,Ana Torres,Tablet,Tienda fisica,14,355.95,15.0,4983.30

In [14]:
filtrar_ventas(df, 'Sur', 'Accesorios', 100)

Empty DataFrame
Columns: [id_venta, mes, region, vendedor, categoria, canal, cantidad, precio_unit, descuento, monto_bruto]
Index: []

In [15]:
resumen = df.groupby('region').agg(
    total_monto=('monto_bruto', 'sum'),
    promedio=('monto_bruto', 'mean'),
    maximo=('monto_bruto', 'max'),
    minimo=('monto_bruto', 'min'),
    conteo=('monto_bruto', 'count')
).round(2)

In [16]:
resumen = resumen.reset_index().sort_values(by='total_monto')

In [17]:
df_rm = df.groupby(['region', 'mes']).agg(
    total_monto=('monto_bruto', 'sum'),
    total_cantidad=('cantidad', 'sum')
).reset_index()

df_rm.head(10)

   region      mes  total_monto  total_cantidad
0  Centro    Abril     10390.50              64
1  Centro    Enero      8727.16              33
2  Centro  Febrero      6330.77              37
3  Centro    Junio     51903.36             120
4  Centro    Marzo     16884.87              81
5  Centro     Mayo     16018.08              62
6    Este    Abril     29469.73             111
7    Este    Enero     21131.64              64
8    Este  Febrero     25411.30              56
9    Este    Junio     25126.33              60

In [18]:
df.groupby('vendedor')['monto_bruto'].sum().idxmax()

'Camila Vega'

In [19]:
df_cat = df.groupby('categoria').agg(
    precio_promedio=('precio_unit', 'mean'),
    cantidad_total=('cantidad', 'sum')
).sort_values(by='precio_promedio')

In [20]:
#Sirve para convertir el indice en columna normal
#Se usa cuando se necesita varias metricas a la vez y permite renombrar columnas directamente